apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vignette-legacy
  labels:
    app: vignette-legacy
  namespace: prod
spec:
  jobLabel: job
  targetLabels:
  - instance
  selector:
    matchLabels:
      app: vignette-legacy
  namespaceSelector:
    matchNames:
    - ops
  endpoints:
  - port: http-metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vignette-legacy
  labels:
    app: vignette-legacy
    prometheus: prod
    role: alert-rules
  namespace: prod
spec:
  groups:
    - name: "vignette-legacy.rules"
      rules:
        - alert: "vignette-legacy-exceptions-ratio"
          expr: "100 * sum by(instance) (rate(vignette_exception_count_total{job=\"vignette-legacy\"}[10m])) / sum by(instance) (rate(vignette_request_count_total{job=\"vignette-legacy\"}[10m])) > 1"
          labels:
            severity: "warning"
            slack_channel: "#services-alerts"
            team: "services"
            pd: "send"
          annotations:
            summary: "legacy vignette throwing a lot of exceptions"
            description: "vignette: {{ $value | humanize }}% of requests to pod {{ $labels.pod }} fail with 5xx response"
